/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

/* adapt to current compiler/host processor */

#include <cstdint>
#include <cstddef>

#define MayInline inline __attribute__((always_inline))
#define MayNotInline __attribute__((noinline))
#define SmallGlobals 0
#define cIncludeUnused 0
#define UnusedParam(p) (void) p

/* --- integer types ---- */

using ui3b = uint8_t;
#define HaveRealui3b 1

using si3b = int8_t;
#define HaveRealsi3b 1

using ui4b = uint16_t;
#define HaveRealui4b 1

using si4b = int16_t;
#define HaveRealsi4b 1

using ui5b = uint32_t;
#define HaveRealui5b 1

using si5b = int32_t;
#define HaveRealsi5b 1

#define HaveRealui6b 0
#define HaveRealsi6b 0

/* --- integer representation types ---- */

using ui3r = uint8_t;
#define ui3beqr 1

using si3r = int8_t;
#define si3beqr 1

using ui4r = uint16_t;
#define ui4beqr 1

using si4r = int16_t;
#define si4beqr 1

using ui5r = uint32_t;
#define ui5beqr 1

using si5r = int32_t;
#define si5beqr 1

using si6r = int64_t;
using si6b = int64_t;
using ui6r = uint64_t;
using ui6b = uint64_t;
#define LIT64(a) a##ULL
