#!/bin/bash
# Build the maxivmac INIT with the current git version stamped in.
#
# Usage: ./build-init.sh [--disk DISK.hfs] [--mac macii-7.mac]
#
# Prerequisites:
#   - A working maxivmac build in bld/macos/
#   - A boot disk with THINK C 5.0 and an existing (old) INIT

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INIT_DIR="$SCRIPT_DIR/macsrc/init"

# Generate version.h from git
VERSION=$(git describe --tags --match "v*" --always 2>/dev/null || echo "dev-unknown")
if [[ ! "$VERSION" =~ ^v ]]; then
    VERSION="dev-$VERSION"
fi

cat > "$INIT_DIR/version.h" << EOF
/* Auto-generated by build-init.sh — do not edit */
#ifndef VERSION_H
#define VERSION_H
#define kInitVersion "\p${VERSION}"
#endif
EOF

echo "Stamped INIT version: $VERSION"
echo "Run the emulator with shared drive pointing at macsrc/init/"
echo "and use build.dbg to compile."
