/*
	see comment in OSGCOMUD.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#pragma once

#define dbglog_HAVE 1
#define WantAbnormalReports 0

#define NumDrives 6

/* vMacScreenWidth/Height/Depth are now runtime — see platform.h */
/* kROM_Size is now runtime — see MachineConfig::romSize */

#define NumPbufs 4

#define EmLocalTalk 0
