/*
	see comment in PICOMMON.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#pragma once

/* CPU feature flags — always 1 so all instruction code compiles.
   Runtime selection via MachineConfig::use68020/emFPU/emMMU +
   dispatch table fixup in M68KITAB_setup(). */
#define USE_68020 1
#define EM_FPU 1
#define EM_MMU 1

/* kMyClockMult is now runtime — see MachineConfig::clockMult */

#define WANT_CYC_BY_PRI_OP 1
#define WANT_CLOSER_CYC 1

/* kAutoSlowSubTicks/kAutoSlowTime are now runtime — see MachineConfig */

#define INCLUDE_EXTN_PBUFS 1
#define INCLUDE_EXTN_HOST_TEXT_CLIP_EXCHANGE 1

#define SONY_SUPPORT_DC42 1
#define SONY_SUPPORT_TAGS 1
#define SONY_WANT_CHECKSUMS_UPDATED 1
#define SONY_VERIFY_CHECKSUMS 0
/* CaretBlinkTime and DoubleClickTime are model-dependent, set in rtc.cpp */

#include "core/wire_macros.h"

/* VIA configuration now in VIAConfig (machine_config.h) */

/* kExtn_Block_Base/kExtn_ln2Spc are now runtime — see MachineConfig */

/* kROM_Base/kROM_ln2Spc are now runtime — see MachineConfig::romBase */

#define WANT_DISASM 1
#define EXTRA_ABNORMAL_REPORTS 0
