/*
	see comment in PICOMMON.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

/* Device-enable flags still needed as compile-time guards because
   pmu.cpp, keyboard.cpp, sound.cpp have cross-subsystem VIA
   dependencies that prevent always-compiling their bodies.
   The rest are now runtime via MachineConfig. */
#define EmClassicKbrd 0
#define EmPMU 0
#define EmClassicSnd 0

/* CPU feature flags — must stay compile-time for hot-path performance */
#define Use68020 1
#define EmFPU 1
#define EmMMU 0

#define kMyClockMult 2

#define WantCycByPriOp 1
#define WantCloserCyc 1

#define kAutoSlowSubTicks 16384
#define kAutoSlowTime 60

#define kRAMa_Size 0x00400000
#define kRAMb_Size 0x00400000

#define kVidMemRAM_Size 0x00080000

#define kVidROM_Size 0x000800

#define MaxATTListN 20
#define IncludeExtnPbufs 1
#define IncludeExtnHostTextClipExchange 1

#define Sony_SupportDC42 1
#define Sony_SupportTags 1
#define Sony_WantChecksumsUpdated 1
#define Sony_VerifyChecksums 0
#define CaretBlinkTime 0x08
#define SpeakerVol 0x07
#define DoubleClickTime 0x08
#define MenuBlink 0x03
#define AutoKeyThresh 0x06
#define AutoKeyRate 0x03
#define pr_HilColRed 0x0000
#define pr_HilColGreen 0x0000
#define pr_HilColBlue 0x0000


/* the Wire variables are 1/0, not true/false */

/* Wire IDs now come from the superset enum in wire_ids.h.
   The #define aliases below provide backward compatibility. */
#include "core/wire_ids.h"

#define SoundDisable (Wires[Wire_SoundDisable])
#define SoundVolb0 (Wires[Wire_SoundVolb0])
#define SoundVolb1 (Wires[Wire_SoundVolb1])
#define SoundVolb2 (Wires[Wire_SoundVolb2])

#define VIA1_iA0 (Wires[Wire_VIA1_iA0])
#define VIA1_iA1 (Wires[Wire_VIA1_iA1])
#define VIA1_iA2 (Wires[Wire_VIA1_iA2])
#define VIA1_iA3 (Wires[Wire_VIA1_iA3])
#define VIA1_iA4 (Wires[Wire_VIA1_iA4])
#define VIA1_iA5 (Wires[Wire_VIA1_iA5])
#define VIA1_iA6 (Wires[Wire_VIA1_iA6])
#define VIA1_iA7 (Wires[Wire_VIA1_iA7])

#define VIA1_iB0 (Wires[Wire_VIA1_iB0])
#define VIA1_iB1 (Wires[Wire_VIA1_iB1])
#define VIA1_iB2 (Wires[Wire_VIA1_iB2])
#define VIA1_iB3 (Wires[Wire_VIA1_iB3])
#define VIA1_iB4 (Wires[Wire_VIA1_iB4])
#define VIA1_iB5 (Wires[Wire_VIA1_iB5])
#define VIA1_iB6 (Wires[Wire_VIA1_iB6])
#define VIA1_iB7 (Wires[Wire_VIA1_iB7])

#define VIA1_iCB2 (Wires[Wire_VIA1_iCB2])

/* Named signal aliases */
#define MemOverlay (Wires[Wire_VIA1_iA4])
#define IWMvSel (Wires[Wire_VIA1_iA5])
#define SCCwaitrq (Wires[Wire_VIA1_iA7])
#define RTCdataLine (Wires[Wire_VIA1_iB0])
#define RTCclock (Wires[Wire_VIA1_iB1])
#define RTCunEnabled (Wires[Wire_VIA1_iB2])
#define ADB_Int (Wires[Wire_VIA1_iB3])
#define ADB_st0 (Wires[Wire_VIA1_iB4])
#define ADB_st1 (Wires[Wire_VIA1_iB5])
#define ADB_Data (Wires[Wire_VIA1_iCB2])
#define Addr32 (Wires[Wire_VIA2_iB3])

/* VIA2 aliases */
#define VIA2_iA0 (Wires[Wire_VIA2_iA0])
#define VIA2_iA6 (Wires[Wire_VIA2_iA6])
#define VIA2_iA7 (Wires[Wire_VIA2_iA7])
#define VIA2_iB2 (Wires[Wire_VIA2_iB2])
#define VIA2_iB3 (Wires[Wire_VIA2_iB3])
#define VIA2_iB7 (Wires[Wire_VIA2_iB7])
#define VIA2_iCB2 (Wires[Wire_VIA2_iCB2])

#define VIA2_InterruptRequest (Wires[Wire_VIA2_InterruptRequest])
#define VIA1_InterruptRequest (Wires[Wire_VIA1_InterruptRequest])
#define SCCInterruptRequest (Wires[Wire_SCCInterruptRequest])
#define ADBMouseDisabled (Wires[Wire_ADBMouseDisabled])
#define Vid_VBLinterrupt (Wires[Wire_VBLinterrupt])
#define Vid_VBLintunenbl (Wires[Wire_VBLintunenbl])

/* ChangeNtfy aliases — map wire names to callback function names */
#define VIA1_iA4_ChangeNtfy MemOverlay_ChangeNtfy
#define VIA1_iB0_ChangeNtfy RTCdataLine_ChangeNtfy
#define VIA1_iB1_ChangeNtfy RTCclock_ChangeNtfy
#define VIA1_iB2_ChangeNtfy RTCunEnabled_ChangeNtfy
#define VIA1_iB4_ChangeNtfy ADBstate_ChangeNtfy
#define VIA1_iB5_ChangeNtfy ADBstate_ChangeNtfy
#define VIA1_iCB2_ChangeNtfy ADB_DataLineChngNtfy
#define VIA2_iA7_ChangeNtfy Addr32_ChangeNtfy
#define VIA2_iA6_ChangeNtfy Addr32_ChangeNtfy
#define VIA2_iB2_ChangeNtfy PowerOff_ChangeNtfy
#define VIA2_iB3_ChangeNtfy Addr32_ChangeNtfy
#define VIA2_interruptChngNtfy VIAorSCCinterruptChngNtfy
#define VIA1_interruptChngNtfy VIAorSCCinterruptChngNtfy
#define SCCinterruptChngNtfy VIAorSCCinterruptChngNtfy


/* VIA configuration now in VIAConfig (machine_config.h) */

#define Mouse_Enabled() (! ADBMouseDisabled)

#define VIA1_iCA1_PulseNtfy VIA1_iCA1_Sixtieth_PulseNtfy
#define Sixtieth_PulseNtfy VIA1_iCA1_Sixtieth_PulseNtfy

#define VIA1_iCA2_PulseNtfy VIA1_iCA2_RTC_OneSecond_PulseNtfy
#define RTC_OneSecond_PulseNtfy VIA1_iCA2_RTC_OneSecond_PulseNtfy

#define VIA2_iCA1_PulseNtfy VIA2_iCA1_Vid_VBLinterrupt_PulseNtfy
#define Vid_VBLinterrupt_PulseNotify VIA2_iCA1_Vid_VBLinterrupt_PulseNtfy

#define VIA2_iCB1_PulseNtfy VIA2_iCB1_ASC_interrupt_PulseNtfy
#define ASC_interrupt_PulseNtfy VIA2_iCB1_ASC_interrupt_PulseNtfy

#define GetSoundInvertTime VIA1_GetT1InvertTime

#define ADB_ShiftInData VIA1_ShiftOutData
#define ADB_ShiftOutData VIA1_ShiftInData

#define kExtn_Block_Base 0x50F0C000
#define kExtn_ln2Spc 5

#define kROM_Base 0x00800000
#define kROM_ln2Spc 20

#define WantDisasm 0
#define ExtraAbnormalReports 0
