/*
	see comment in PICOMMON.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#pragma once

/* CPU feature flags — always 1 so all instruction code compiles.
   Runtime selection via MachineConfig::use68020/emFPU/emMMU +
   dispatch table fixup in M68KITAB_setup(). */
#define Use68020 1
#define EmFPU 1
#define EmMMU 1

/* kMyClockMult is now runtime — see MachineConfig::clockMult */

#define WantCycByPriOp 1
#define WantCloserCyc 1

/* kAutoSlowSubTicks/kAutoSlowTime are now runtime — see MachineConfig */

#define IncludeExtnPbufs 1
#define IncludeExtnHostTextClipExchange 1

constexpr int NumDrives = 6;
constexpr int NumPbufs = 4;

#define Sony_SupportDC42 1
#define Sony_SupportTags 1
#define Sony_WantChecksumsUpdated 1
#define Sony_VerifyChecksums 0
/* CaretBlinkTime and DoubleClickTime are model-dependent, set in rtc.cpp */

#include "core/wire_macros.h"

/* VIA configuration now in VIAConfig (machine_config.h) */

/* kExtn_Block_Base/kExtn_ln2Spc are now runtime — see MachineConfig */

/* kROM_Base/kROM_ln2Spc are now runtime — see MachineConfig::romBase */

#define WantDisasm 1
#define ExtraAbnormalReports 0
