/*
	see comment in PICOMMON.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#pragma once

/* CPU feature flags — always 1 so all instruction code compiles.
   Runtime selection via MachineConfig::use68020/emFPU/emMMU +
   dispatch table fixup in M68KITAB_setup(). */

/* kMyClockMult is now runtime — see MachineConfig::clockMult */


/* kAutoSlowSubTicks/kAutoSlowTime are now runtime — see MachineConfig */


constexpr int NumDrives = 6;
constexpr int NumPbufs = 4;


/* CaretBlinkTime and DoubleClickTime are model-dependent, set in rtc.cpp */

#include "core/wire_macros.h"

/* VIA configuration now in VIAConfig (machine_config.h) */

/* kExtn_Block_Base/kExtn_ln2Spc are now runtime — see MachineConfig */

/* kROM_Base/kROM_ln2Spc are now runtime — see MachineConfig::romBase */
