/*
	Compiler/platform configuration.
	
	This file is automatically generated by the build system.
	Avoid changing this file manually unless you know what you're doing.
*/

#pragma once

#include <cstdint>
#include <cstddef>

/* Optimization hints — compiler may override */

#define C_INCLUDE_UNUSED 0
#define UNUSED(p) (void)(p)
#define UNUSED(p) (void)(p)

/* Endian/alignment support */
#ifndef BIG_ENDIAN_UNALIGNED
#define BIG_ENDIAN_UNALIGNED 0
#endif

#ifndef LITTLE_ENDIAN_UNALIGNED
#define LITTLE_ENDIAN_UNALIGNED 0
#endif

#ifndef HAVE_ASR
#define HAVE_ASR 0
#endif

#ifndef HAVE_SWAP_UI5R
#define HAVE_SWAP_UI5R 0
#endif

/* 64-bit integer types (for FPU emulation) */
using si6r = int64_t;
using si6b = int64_t;
using ui6r = uint64_t;
using ui6b = uint64_t;
#define LIT64(a) a##ULL
