/*
	Compiler/platform configuration.
	
	This file is automatically generated by the build system.
	Avoid changing this file manually unless you know what you're doing.
*/

#pragma once

#include <cstdint>
#include <cstddef>

/* Optimization hints — compiler may override */

#define UNUSED(p) (void)(p)
#define UNUSED(p) (void)(p)

#ifndef HAVE_ASR
#define HAVE_ASR 0
#endif

/* 64-bit integer types (for FPU emulation) */
using si6r = int64_t;
using si6b = int64_t;
using ui6r = uint64_t;
using ui6b = uint64_t;
#define LIT64(a) a##ULL
